import React, { useState, useEffect, useCallback } from 'react';
import { io } from 'socket.io-client';
import { NoticeAPI, SuggestionAPI, NotificationAPI } from '../api/communication';
import { useNotificationLogState, isExpired5Days } from '../components/common/common_admin_notification';
import { formatDateByLang } from '../components/common/common_common';
import { useAuthContext } from '../contexts/AuthContext';

const SERVER_URL = process.env.REACT_APP_SERVER_URL || 'http://localhost:5000';

const devLog = (...args) => {
  //  if (process.env.NODE_ENV === 'development') console.log(...args);
};

// ─────────────────────────────────────────────────────────────
// 공통 포맷터 (useEffect 여러 곳에서 재사용)
// ─────────────────────────────────────────────────────────────

/** DB 공지 레코드 → 앱 내부 형식 */
const formatNotice = (notice) => {
  let attachments = notice.attachments || [];
  if (attachments.length > 0 && typeof attachments[0] === 'string') {
    attachments = attachments.map((fileName) => ({
      name: fileName,
      url: '',
      size: '',
    }));
  }
  return {
    id: notice._id,
    _id: notice._id,
    title: notice.title,
    content: notice.content,
    author: notice.author,
    authorId: notice.authorId,
    category: notice.category,
    priority: notice.priority,
    files: attachments,
    attachments,
    date: notice.createdAt
      ? new Date(notice.createdAt).toISOString().slice(0, 10)
      : '',
    createdAt: notice.createdAt,
    updatedAt: notice.updatedAt,
    views: notice.views || 0,
    viewCount: notice.viewCount || 0,
    viewedBy: notice.viewedBy || [],
    isImportant: notice.isImportant || false,
    isScheduled: notice.isScheduled || false,
    scheduledDateTime: notice.scheduledDateTime,
  };
};

/** DB 건의 레코드 → 앱 내부 형식 */
const formatSuggestion = (suggestion) => ({
  id: suggestion._id,
  _id: suggestion._id,
  employeeId: suggestion.employeeId,
  name: suggestion.name || '',
  department: suggestion.department || '',
  type: suggestion.type,
  title: suggestion.title,
  content: suggestion.content,
  status: suggestion.status,
  remark: suggestion.remark || '',
  approver: suggestion.approver,
  approvalDate: formatDateByLang(suggestion.approvalDate),
  applyDate:
    suggestion.applyDate ||
    (suggestion.createdAt
      ? new Date(suggestion.createdAt).toISOString().slice(0, 10)
      : ''),
  createdAt: suggestion.createdAt,
  date:
    suggestion.applyDate ||
    (suggestion.createdAt
      ? new Date(suggestion.createdAt).toISOString().slice(0, 10)
      : ''),
});

/** DB 알림 목록 → 정기/실시간 분류 */
const splitNotifications = (notifications) => {
  const mapped = notifications.map((n) => ({ ...n, id: n._id || n.id }));
  const regularList = mapped.filter((n) => n.notificationType === '정기');
  const realtimeList = mapped.filter(
    (n) =>
      n.notificationType === '실시간' || n.notificationType === '시스템'
  );
  return {
    regularList,
    realtimeList: realtimeList.map((log) => ({
      ...log,
      status:
        log.notificationType === '시스템' ? '진행중' : log.status || '진행중',
      isAutoGenerated: log.notificationType === '시스템',
    })),
  };
};

// ─────────────────────────────────────────────────────────────
// 커스텀 훅
// ─────────────────────────────────────────────────────────────

/**
 * 공지/알림/건의 데이터 관리 커스텀 훅
 * App.js [2_관리자 모드] 2.4·2.7·2.10 + [1_공통] 1.3.8 블록에서 추출
 *
 * currentUser는 AuthContext에서 직접 소비
 *
 * 반환값: 아래 return 블록 참조
 *
 * NOTE:
 * - useNotificationHandlers 는 App.js에 유지 (employeeNotifications 의존)
 * - 전역 Socket useEffect 는 App.js에 유지 (employee·leave·attendance 혼합)
 * - cleanupExpiredNotifications 은 이 훅 내부로 이동 (isExpired5Days standalone export로 해결)
 * - updateEmployeeNotifications timer useEffect 는 App.js에 유지 (handler 의존)
 */
const useCommunicationData = () => {
  const { currentUser } = useAuthContext();

  // ─── 공지 STATE ─────────────────────────────────────────────
  const [notices, setNotices] = useState([]);

  // ─── 건의 STATE ─────────────────────────────────────────────
  const [suggestions, setSuggestions] = useState([]);
  const [suggestionPage, setSuggestionPage] = useState(1);

  // ─── 알림 데이터 STATE ───────────────────────────────────────
  //---[2_관리자 모드] 2.4_알림 관리 STATE---//
  const [regularNotifications, setRegularNotifications] = useState([]);
  const [realtimeNotifications, setRealtimeNotifications] = useState([]);
  const [notificationLogs, setNotificationLogs] = useState([]);

  // *[2_관리자 모드] 2.4_알림 로그 state (점진적 더보기)*
  const {
    visibleLogCount,
    setVisibleLogCount,
    handleLoadMoreLogs,
    handleCollapseLogs,
  } = useNotificationLogState();

  // *[2_관리자 모드] 2.4.1_알림 로그 검색*
  const [notificationLogSearch, setNotificationLogSearch] = useState({
    year: '',
    month: '',
    recipient: '',
    titleOrContent: '',
    type: '',
  });

  // ─── 알림 팝업 STATE ─────────────────────────────────────────
  // *[2_관리자 모드] 2.4.3_알림 팝업 상태*
  const [
    showAddRegularNotificationPopup,
    setShowAddRegularNotificationPopup,
  ] = useState(false);
  const [
    showAddRealtimeNotificationPopup,
    setShowAddRealtimeNotificationPopup,
  ] = useState(false);
  const [showAddNotificationPopup, setShowAddNotificationPopup] =
    useState(false);
  const [알림유형, set알림유형] = useState('정기');

  // *[2_관리자 모드] 2.4.4_알림 편집 팝업 상태*
  const [
    showEditRegularNotificationPopup,
    setShowEditRegularNotificationPopup,
  ] = useState(false);
  const [
    showEditRealtimeNotificationPopup,
    setShowEditRealtimeNotificationPopup,
  ] = useState(false);
  const [editingRegularNotification, setEditingRegularNotification] =
    useState(null);
  const [editingRealtimeNotification, setEditingRealtimeNotification] =
    useState(null);

  // *[2_관리자 모드] 2.4.5_알림 폼 데이터*
  const [regularNotificationForm, setRegularNotificationForm] = useState({
    title: '',
    content: '',
    status: '진행중',
    startDate: '',
    endDate: '',
    repeatCycle: '특정일',
    recipients: { type: '전체', value: '전체직원', selectedEmployees: [] },
  });
  const [realtimeNotificationForm, setRealtimeNotificationForm] = useState({
    title: '',
    content: '',
    status: '진행중',
    startDate: '',
    endDate: '',
    repeatCycle: '특정일',
    recipients: { type: '전체', value: '전체직원', selectedEmployees: [] },
  });

  // *[2_관리자 모드] 2.4.6_반복 설정 모달*
  const [showRecurringSettingsModal, setShowRecurringSettingsModal] =
    useState(false);
  const [recurringSettings, setRecurringSettings] = useState({
    반복주기_숫자: 1,
    반복주기_단위: '일',
    반복시작일: '',
    반복종료일: '',
    반복시간: '09:00',
    반복요일: [],
    반복일자: 1,
    반복월: 1,
  });
  const [currentFormType, setCurrentFormType] = useState('');

  // ─── 만료 판정 유틸 ──────────────────────────────────────────
  // *[1_공통] 1.3.8.3_정기 알림 만료 판정*
  const isRegularExpired = (n) => {
    if (!n?.endDate) return false;
    const del = new Date(n.endDate);
    del.setDate(del.getDate() + 1);
    del.setHours(0, 0, 0, 0);
    return new Date() >= del;
  };

  // *[1_공통] 1.3.8.4_알림 로그 3년 체크*
  const isLogOlderThan3Years = (createdAt) => {
    if (!createdAt) return false;
    try {
      const logDate = new Date(createdAt);
      const threeYearsAgo = new Date();
      threeYearsAgo.setFullYear(threeYearsAgo.getFullYear() - 3);
      return logDate < threeYearsAgo;
    } catch (e) {
      return false;
    }
  };

  // *[1_공통] 1.3.8.5_알림 로그 3년 삭제*
  const cleanupOldLogs = () => {
    setNotificationLogs((prev) =>
      prev.filter((log) => !isLogOlderThan3Years(log.createdAt))
    );
  };

  // *[1_공통] 1.3.8.6_만료 알림 정리*
  const cleanupExpiredRegulars = () => {
    try {
      const now = new Date().toLocaleString('ko-KR');

      setRegularNotifications((prev) => {
        const expired = prev.filter((n) => isRegularExpired(n));
        const active = prev.filter((n) => !isRegularExpired(n));

        if (expired.length > 0) {
          const expiredLogs = expired.map((n) => ({
            id: `expire_${n.id}`,
            type: '정기알림',
            title: n.title,
            status: '만료됨',
            createdAt: now,
          }));
          setNotificationLogs((prevLogs) => [...expiredLogs, ...prevLogs]);
        }

        return active;
      });

      cleanupOldLogs();
    } catch (e) {
      console.error('만료 정기알림 정리 오류', e);
    }
  };

  // ─── useEffect F: 초기 만료 알림 정리 ────────────────────────
  // *[1_공통] 1.3.8.8_만료 알림 초기 정리 useEffect*
  useEffect(() => {
    cleanupExpiredRegulars();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ─── useEffect B: 로그인 후 알림 재조회 ───────────────────────
  // *[1_공통] 로그인 후 알림 재조회 — 일반직원: 본인 수신 알림만, 관리자: 전체*
  useEffect(() => {
    if (!currentUser) return;

    const reloadNotificationsForUser = async () => {
      try {
        let notifications;
        if (currentUser.isAdmin) {
          notifications = await NotificationAPI.list();
        } else {
          devLog(`🔄 [알림 B안] 본인 알림 조회: ${currentUser.name}`);
          notifications = await NotificationAPI.list(
            null,
            currentUser.name,
            currentUser.department,
            currentUser.position,
            currentUser.role
          );
        }
        if (notifications && Array.isArray(notifications)) {
          const { regularList, realtimeList } =
            splitNotifications(notifications);
          setRegularNotifications(regularList);
          setRealtimeNotifications(realtimeList);
          const allLogs = [...regularList, ...realtimeList].map((n) => ({
            id: n.id,
            type: n.notificationType,
            title: n.title,
            content: n.content,
            recipients: n.recipients?.value || '전체직원',
            repeatType: n.repeatCycle,
            createdAt: n.createdAt,
            completedAt: n.completedAt,
          }));
          setNotificationLogs(allLogs);
          devLog(
            `✅ [알림 B안] 로드 완료: 정기=${regularList.length}, 실시간=${realtimeList.length}`
          );
        }
      } catch (error) {
        devLog('❌ [알림 B안] 로드 실패:', error);
      }
    };

    reloadNotificationsForUser();
  }, [currentUser?.id]); // [4차 패치] [currentUser] → [currentUser?.id]

  // ─── useEffect C: 건의사항 DB 로드 ────────────────────────────
  // *[1_공통] 건의사항 데이터 DB에서 로드*
  useEffect(() => {
    const loadSuggestionsFromDB = async () => {
      if (!currentUser || !currentUser.id) {
        devLog('⚠️ currentUser 정보 없음 - 건의사항 로드 스킵');
        return;
      }

      try {
        devLog('🔄 DB에서 건의사항 데이터 로딩 시작...');
        const isAdmin =
          currentUser.isAdmin === true || currentUser.role === 'admin';
        const dbSuggestions = await SuggestionAPI.list(
          isAdmin ? null : currentUser.id,
          isAdmin ? 'admin' : null
        );

        if (Array.isArray(dbSuggestions) && dbSuggestions.length > 0) {
          setSuggestions(dbSuggestions.map(formatSuggestion));
          devLog(
            `✅ DB에서 건의사항 ${dbSuggestions.length}건 로드 완료`
          );
        } else {
          devLog('⚠️ DB에 건의사항 데이터 없음');
          setSuggestions([]);
        }
      } catch (error) {
        console.error('❌ [건의사항 로드] DB 건의사항 로드 실패:', error);
        console.error(
          '❌ [건의사항 로드] 에러 상세:',
          error.message,
          error.stack
        );
        setSuggestions([]);
      }
    };

    loadSuggestionsFromDB();
  }, [currentUser?.id]); // [4차 패치] [currentUser] → [currentUser?.id]

  // ─── useEffect A: 공지 Socket + loadNoticesFromDB ─────────────
  // *[1_공통] 공지사항 데이터 DB에서 로드 및 Socket.io 실시간 업데이트*
  useEffect(() => {
    if (!currentUser) return;

    const loadNoticesFromDB = async () => {
      try {
        devLog('🔄 DB에서 공지사항 데이터 로딩 시작...');
        const includeScheduled = currentUser?.role === 'admin';
        const isStaff =
          !currentUser?.isAdmin && currentUser?.role !== 'admin';
        const dbNotices = await NoticeAPI.list(includeScheduled, isStaff);

        if (Array.isArray(dbNotices) && dbNotices.length > 0) {
          setNotices(dbNotices.map(formatNotice));
          devLog(`✅ DB에서 공지사항 ${dbNotices.length}건 로드 완료`);
        } else {
          devLog('⚠️ DB에 공지사항 데이터 없음 - 기존 데이터 유지');
        }
      } catch (error) {
        console.error('❌ DB 공지사항 로드 실패:', error);
        devLog('⚠️ 공지사항 API 실패 - 기존 데이터 유지');
      }
    };

    // [3차 패치] socket 즉시 연결 (2차 패치의 500ms 지연 롤백)
    const noticeSocket = io(SERVER_URL, {
      reconnectionDelay: 1000,
      reconnectionDelayMax: 5000,
      transports: ['websocket', 'polling'],
    });

    let noticeSocketConnected = false;
    noticeSocket.on('connect', () => {
      devLog('🔌 [공지 Socket] 연결됨');
      if (noticeSocketConnected) {
        devLog('🔄 [공지 Socket] 재연결 - 공지사항 재조회');
        loadNoticesFromDB();
      }
      noticeSocketConnected = true;
    });

    noticeSocket.on('notice-published', () => {
      devLog('📢 예약 공지사항 자동 게시 - 공지사항 재조회');
      loadNoticesFromDB();
    });

    noticeSocket.on('notice-created', (data) => {
      devLog(`✨ [공지 Socket] 공지사항 등록됨: ${data.title}`);
      loadNoticesFromDB();
    });

    noticeSocket.on('notice-updated', (data) => {
      devLog(`✏️ [공지 Socket] 공지사항 수정됨: ${data.title}`);
      loadNoticesFromDB();
    });

    noticeSocket.on('notice-deleted', (data) => {
      devLog(`🗑️ [공지 Socket] 공지사항 삭제됨: ${data.noticeId}`);
      loadNoticesFromDB();
    });

    noticeSocket.on('disconnect', () => {
      devLog('🔌 [공지 Socket] 연결 해제됨');
    });

    return () => {
      noticeSocket.removeAllListeners();
      if (noticeSocket.connected) {
        noticeSocket.disconnect();
      }
    };
  }, [currentUser?.id]);

  // ─── useEffect D: Staff 탭 재활성화 시 공지/알림 재조회 ──────
  // *[3_일반직원 모드] 탭 재활성화 시 공지/알림 재조회*
  useEffect(() => {
    if (!currentUser || currentUser.isAdmin) return;

    const handleStaffVisibilityChange = async () => {
      if (document.hidden) return;
      devLog('👁️ [직원 탭 재활성화] 공지/알림 재조회');

      try {
        const dbNotices = await NoticeAPI.list(false, true); // lite=true
        if (Array.isArray(dbNotices) && dbNotices.length > 0) {
          setNotices(dbNotices.map(formatNotice));
        }
      } catch (err) {
        console.error('❌ [직원 탭 재활성화] 공지 재조회 실패:', err);
      }

      try {
        const notifications = await NotificationAPI.list(
          null,
          currentUser.name,
          currentUser.department,
          currentUser.position,
          currentUser.role
        );
        if (notifications && Array.isArray(notifications)) {
          const { regularList, realtimeList } =
            splitNotifications(notifications);
          setRegularNotifications(regularList);
          setRealtimeNotifications(realtimeList);
        }
      } catch (err) {
        console.error('❌ [직원 탭 재활성화] 알림 재조회 실패:', err);
      }
    };

    document.addEventListener('visibilitychange', handleStaffVisibilityChange);
    return () =>
      document.removeEventListener(
        'visibilitychange',
        handleStaffVisibilityChange
      );
  }, [currentUser?.id]); // [4차 패치] [currentUser] → [currentUser?.id]

  // ─── 만료 알림 정리 (regularNotifications / realtimeNotifications) ────────
  // *[1_공통] 1.3.8.2_만료 알림 정리 함수*
  const cleanupExpiredNotifications = useCallback(() => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    setRegularNotifications((prev) =>
      prev.filter((n) => {
        if (isExpired5Days(n.createdAt)) return false;
        if (n.endDate) {
          const endDate = new Date(n.endDate);
          endDate.setHours(23, 59, 59, 999);
          if (endDate < today) return false;
        }
        return true;
      })
    );

    setRealtimeNotifications((prev) =>
      prev.filter((n) => !isExpired5Days(n.createdAt))
    );
  }, []);

  // *[1_공통] 1.3.8.2.1_만료 알림 정리 6시간 인터벌*
  useEffect(() => {
    const cleanupInterval = setInterval(() => {
      cleanupExpiredNotifications();
    }, 6 * 60 * 60 * 1000);

    return () => clearInterval(cleanupInterval);
  }, [cleanupExpiredNotifications]);

  // ─── 반환 ────────────────────────────────────────────────────
  return {
    // 공지
    notices,
    setNotices,

    // 건의
    suggestions,
    setSuggestions,
    suggestionPage,
    setSuggestionPage,

    // 알림 데이터
    regularNotifications,
    setRegularNotifications,
    realtimeNotifications,
    setRealtimeNotifications,
    notificationLogs,
    setNotificationLogs,

    // 알림 로그 더보기 (useNotificationLogState)
    visibleLogCount,
    setVisibleLogCount,
    handleLoadMoreLogs,
    handleCollapseLogs,

    // 알림 로그 검색
    notificationLogSearch,
    setNotificationLogSearch,

    // 알림 팝업
    showAddRegularNotificationPopup,
    setShowAddRegularNotificationPopup,
    showAddRealtimeNotificationPopup,
    setShowAddRealtimeNotificationPopup,
    showAddNotificationPopup,
    setShowAddNotificationPopup,
    알림유형,
    set알림유형,

    // 알림 편집 팝업
    showEditRegularNotificationPopup,
    setShowEditRegularNotificationPopup,
    showEditRealtimeNotificationPopup,
    setShowEditRealtimeNotificationPopup,
    editingRegularNotification,
    setEditingRegularNotification,
    editingRealtimeNotification,
    setEditingRealtimeNotification,

    // 알림 폼
    regularNotificationForm,
    setRegularNotificationForm,
    realtimeNotificationForm,
    setRealtimeNotificationForm,

    // 반복 설정
    showRecurringSettingsModal,
    setShowRecurringSettingsModal,
    recurringSettings,
    setRecurringSettings,
    currentFormType,
    setCurrentFormType,

    // 만료 관리 함수
    cleanupExpiredRegulars,
    cleanupExpiredNotifications,
  };
};

export default useCommunicationData;
