import { useEffect } from 'react';
import { io } from 'socket.io-client';
import EmployeeAPI from '../api/employee';
import LeaveAPI from '../api/leave';
import { NotificationAPI, SuggestionAPI } from '../api/communication';
import { AttendanceAPI } from '../api/attendance';
import PayrollAPI from '../api/payroll';
import EvaluationAPI from '../api/evaluation';
import { SafetyAccidentAPI } from '../api/safety';
import { ScheduleAPI } from '../api/system';
import HolidayAPI from '../api/holiday';
import {
  calculateEmployeeAnnualLeave as calculateEmployeeAnnualLeaveUtil,
  formatDateByLang,
} from '../components/common/common_common';
import { formatDateToString } from '../utils/dateUtils';

const SERVER_URL = process.env.REACT_APP_SERVER_URL || 'http://localhost:5000';
const devLog = (..._args) => {};

/**
 * *[1_공통] 전역 Socket.io 실시간 업데이트 훅*
 *
 * stale-closure 방지:
 *   leaveRequestsRef, attendanceSheetYearRef, attendanceSheetMonthRef, currentYearRef
 *   → App.js 에서 4개 ref 를 만들고 각 상태와 동기 useEffect 로 연결한 뒤 전달
 *
 * pendingSocketReloadRef 는 visibilitychange 핸들러와 공유하므로 App.js 에서 생성 후 전달
 */
const useSocketSync = ({
  currentUser,
  leaveRequestsRef,
  attendanceSheetYearRef,
  attendanceSheetMonthRef,
  currentYearRef,
  pendingSocketReloadRef,
  setEmployees,
  setRegularNotifications,
  setRealtimeNotifications,
  setSuggestions,
  setLeaveRequests,
  setAttendanceSheetData,
  setPayrollByMonth,
  setEvaluationData,
  setSafetyAccidents,
  setScheduleEvents,
  setCustomHolidays,
}) => {
  // *[1_공통] 전역 Socket.io 실시간 업데이트*
  useEffect(() => {
    if (!currentUser) return;

    const socket = io(SERVER_URL, {
      reconnectionDelay: 1000,
      reconnectionDelayMax: 5000,
      transports: ['websocket', 'polling'],
    });

    let globalSocketConnected = false;
    socket.on('connect', async () => {
      devLog('🔌 [전역 Socket] 연결됨');
      if (globalSocketConnected) {
        // 재연결: 알림 API 1회 재조회 (시스템 타입 포함을 위해 타입 무필터 통합 조회)
        devLog('🔄 [전역 Socket] 재연결 - 알림 재조회');
        try {
          const recipientName = currentUser?.isAdmin ? null : currentUser?.name;
          const dept = currentUser?.isAdmin ? null : currentUser?.department;
          const pos = currentUser?.isAdmin ? null : currentUser?.position;
          const rl = currentUser?.isAdmin ? null : currentUser?.role;
          const notifications = await NotificationAPI.list(null, recipientName, dept, pos, rl);
          if (notifications && Array.isArray(notifications)) {
            const mapped = notifications.map((n) => ({ ...n, id: n._id || n.id }));
            const regularList = mapped.filter((n) => n.notificationType === '정기');
            const realtimeList = mapped.filter((n) =>
              n.notificationType === '실시간' || n.notificationType === '시스템'
            );
            setRegularNotifications(regularList);
            setRealtimeNotifications(realtimeList.map((log) => ({
              ...log,
              status: log.notificationType === '시스템' ? '진행중' : log.status || '진행중',
              isAutoGenerated: log.notificationType === '시스템',
            })));
          }
        } catch (err) {
          console.error('❌ [전역 Socket] 재연결 알림 재조회 실패:', err);
        }
      }
      globalSocketConnected = true;
    });

    // 직원 실시간 업데이트
    const refreshEmployees = async (label) => {
      try {
        const dbEmployees = await EmployeeAPI.list();
        if (dbEmployees && dbEmployees.length > 0) {
          const leaveRequests = leaveRequestsRef.current;
          const formattedEmployees = dbEmployees.map((emp) => {
            const baseEmp = {
              id: emp.employeeId,
              name: emp.name,
              password: emp.password || emp.phone?.slice(-4) || '0000',
              phone: emp.phone,
              department: emp.department,
              subDepartment: emp.subDepartment || '',
              position: emp.position,
              role: emp.role,
              joinDate: formatDateToString(emp.joinDate),
              leaveDate:
                emp.leaveDate && emp.leaveDate !== '1970-01-01T00:00:00.000Z'
                  ? formatDateToString(emp.leaveDate)
                  : '',
              workType: emp.workType,
              payType: emp.salaryType,
              contractType: emp.contractType || '정규',
              status: emp.status,
              address: emp.address,
              lastLogin: emp.lastLogin,
              leaveUsed: emp.leaveUsed,
              usedLeave: emp.usedLeave ?? emp.leaveUsed ?? 0,
            };
            const annualData = calculateEmployeeAnnualLeaveUtil(baseEmp, leaveRequests);
            return {
              ...baseEmp,
              leaveYearStart: annualData.annualStart,
              leaveYearEnd: annualData.annualEnd,
              totalAnnualLeave: annualData.totalAnnual,
              usedAnnualLeave: annualData.usedAnnual,
              remainingAnnualLeave: annualData.remainAnnual,
            };
          });
          setEmployees(formattedEmployees);
        }
      } catch (error) {
        console.error(`❌ [실시간] 직원 데이터 갱신 실패(${label}):`, error);
      }
    };

    socket.on('employee-created', async (data) => {
      devLog(`✨ [실시간] 직원 등록됨: ${data.name}`);
      await refreshEmployees('created');
    });

    socket.on('employee-updated', async (data) => {
      devLog(`✏️ [실시간] 직원 수정됨: ${data.name}`);
      await refreshEmployees('updated');
    });

    socket.on('employee-deleted', async (data) => {
      devLog(`🗑️ [실시간] 직원 삭제됨: ${data.name}`);
      await refreshEmployees('deleted');
    });

    // 알림 실시간 업데이트 (시스템 타입 포함을 위해 타입 무필터 통합 조회)
    const refreshNotifications = async (label) => {
      const recipientName = currentUser?.isAdmin ? null : currentUser?.name;
      const dept = currentUser?.isAdmin ? null : currentUser?.department;
      const pos = currentUser?.isAdmin ? null : currentUser?.position;
      const rl = currentUser?.isAdmin ? null : currentUser?.role;
      const notifications = await NotificationAPI.list(null, recipientName, dept, pos, rl);
      if (notifications && Array.isArray(notifications)) {
        const mapped = notifications.map((n) => ({ ...n, id: n._id || n.id }));
        const regularList = mapped.filter((n) => n.notificationType === '정기');
        const realtimeList = mapped.filter((n) =>
          n.notificationType === '실시간' || n.notificationType === '시스템'
        );
        setRegularNotifications(regularList);
        setRealtimeNotifications(realtimeList.map((log) => ({
          ...log,
          status: log.notificationType === '시스템' ? '진행중' : log.status || '진행중',
          isAutoGenerated: log.notificationType === '시스템',
        })));
      }
    };

    socket.on('notification-created', async (data) => {
      devLog(`✨ [실시간] 알림 등록됨: ${data.title}`);
      try { await refreshNotifications('created'); }
      catch (error) { console.error('❌ [실시간] 알림 데이터 갱신 실패:', error); }
    });

    socket.on('notification-updated', async (data) => {
      devLog(`✏️ [실시간] 알림 수정됨: ${data.title}`);
      try { await refreshNotifications('updated'); }
      catch (error) { console.error('❌ [실시간] 알림 데이터 갱신 실패:', error); }
    });

    socket.on('notification-deleted', async (data) => {
      devLog(`🗑️ [실시간] 알림 삭제됨: ${data.notificationId}`);
      try { await refreshNotifications('deleted'); }
      catch (error) { console.error('❌ [실시간] 알림 데이터 갱신 실패:', error); }
    });

    // 건의사항 실시간 업데이트
    const refreshSuggestions = async (label, allowEmpty = false) => {
      if (!currentUser || !currentUser.id) {
        devLog('⚠️ currentUser 정보 없음 - 건의사항 업데이트 스킵');
        return;
      }
      const isAdmin = currentUser.isAdmin === true || currentUser.role === 'admin';
      const dbSuggestions = await SuggestionAPI.list(
        isAdmin ? null : currentUser.id,
        isAdmin ? 'admin' : null
      );
      if (dbSuggestions && dbSuggestions.length > 0) {
        const formattedSuggestions = dbSuggestions.map((suggestion) => ({
          id: suggestion._id,
          _id: suggestion._id,
          employeeId: suggestion.employeeId,
          name: suggestion.name || '',
          department: suggestion.department || '',
          type: suggestion.type,
          title: suggestion.title,
          content: suggestion.content,
          status: suggestion.status,
          remark: suggestion.remark || '',
          approver: suggestion.approver,
          approvalDate: formatDateByLang(suggestion.approvalDate),
          applyDate:
            suggestion.applyDate ||
            (suggestion.createdAt
              ? new Date(suggestion.createdAt).toISOString().slice(0, 10)
              : ''),
          createdAt: suggestion.createdAt,
          date:
            suggestion.applyDate ||
            (suggestion.createdAt
              ? new Date(suggestion.createdAt).toISOString().slice(0, 10)
              : ''),
        }));
        setSuggestions(formattedSuggestions);
      } else if (allowEmpty) {
        setSuggestions([]);
      }
    };

    socket.on('suggestion-created', async (data) => {
      devLog(`✨ [실시간] 건의사항 등록됨: ${data.title}`);
      if (document.hidden) { pendingSocketReloadRef.current.suggestion = true; return; }
      try { await refreshSuggestions('created'); }
      catch (error) { console.error('❌ [실시간] 건의사항 데이터 갱신 실패:', error); }
    });

    socket.on('suggestion-updated', async (data) => {
      devLog(`✏️ [실시간] 건의사항 수정됨: ${data.title}`);
      if (document.hidden) { pendingSocketReloadRef.current.suggestion = true; return; }
      try { await refreshSuggestions('updated'); }
      catch (error) { console.error('❌ [실시간] 건의사항 데이터 갱신 실패:', error); }
    });

    socket.on('suggestion-deleted', async (data) => {
      devLog(`🗑️ [실시간] 건의사항 삭제됨: ${data.suggestionId}`);
      try { await refreshSuggestions('deleted', true); }
      catch (error) { console.error('❌ [실시간] 건의사항 데이터 갱신 실패:', error); }
    });

    // 연차 실시간 업데이트
    const refreshLeaves = async (label) => {
      const dbLeaves = await LeaveAPI.list();
      if (dbLeaves && dbLeaves.length > 0) {
        const formattedLeaves = dbLeaves.map((leave) => ({
          id: leave._id,
          employeeId: leave.employeeId,
          employeeName: leave.employeeName,
          name: leave.employeeName || leave.name,
          department: leave.department,
          leaveType: leave.leaveType,
          type: leave.leaveType || leave.type,
          startDate: formatDateByLang(leave.startDate),
          endDate: formatDateByLang(leave.endDate),
          days: leave.requestedDays,
          requestedDays: leave.requestedDays,
          reason: leave.reason,
          contact: leave.contact,
          status: leave.status,
          requestDate: formatDateByLang(leave.requestDate || leave.createdAt),
          approvedAt: leave.approvedAt,
          approver: leave.approver,
          approverName: leave.approverName,
          approvedDays: leave.approvedDays,
          rejectedAt: leave.rejectedAt,
          rejectedBy: leave.rejectedBy,
          rejectedByName: leave.rejectedByName,
          rejectionReason: leave.rejectionReason,
          startTime: leave.startTime || null,
          endTime: leave.endTime || null,
        }));
        setLeaveRequests(formattedLeaves);
      }
    };

    socket.on('leave-created', async (data) => {
      devLog(`✨ [실시간] 연차 신청됨: ${data.employeeName} - ${data.leaveType}`);
      if (document.hidden) { pendingSocketReloadRef.current.leave = true; return; }
      try { await refreshLeaves('created'); }
      catch (error) { console.error('❌ [실시간] 연차 데이터 갱신 실패:', error); }
    });

    socket.on('leave-updated', async (data) => {
      devLog(`✏️ [실시간] 연차 수정됨: ${data.employeeName} - ${data.leaveType}`);
      if (document.hidden) { pendingSocketReloadRef.current.leave = true; return; }
      try { await refreshLeaves('updated'); }
      catch (error) { console.error('❌ [실시간] 연차 데이터 갱신 실패:', error); }
    });

    socket.on('leave-status-changed', async (data) => {
      devLog(`🔄 [실시간] 연차 상태 변경됨: ${data.employeeName} - ${data.status}`);
      if (document.hidden) { pendingSocketReloadRef.current.leave = true; return; }
      try { await refreshLeaves('status-changed'); }
      catch (error) { console.error('❌ [실시간] 연차 데이터 갱신 실패:', error); }
    });

    // 근태 실시간 업데이트
    const refreshAttendanceIfCurrent = async (year, month, label) => {
      if (year === attendanceSheetYearRef.current && month === attendanceSheetMonthRef.current) {
        const response = await AttendanceAPI.getMonthlyData(year, month);
        if (response && response.data) {
          setAttendanceSheetData(response.data);
          devLog(`✅ [실시간] 근태 데이터 갱신 완료: ${year}년 ${month}월`);
        }
      }
    };

    socket.on('attendance-bulk-saved', async (data) => {
      devLog(
        `✨ [실시간] 근태 대량 저장됨: ${data.year}년 ${data.month}월 (추가: ${data.inserted}건, 수정: ${data.updated}건)`
      );
      try { await refreshAttendanceIfCurrent(data.year, data.month, 'bulk-saved'); }
      catch (error) { console.error('❌ [실시간] 근태 데이터 갱신 실패:', error); }
    });

    socket.on('attendance-monthly-saved', async (data) => {
      devLog(
        `✨ [실시간] 근태 월별 저장됨: ${data.year}년 ${data.month}월 (${data.successCount}건 성공)`
      );
      try { await refreshAttendanceIfCurrent(data.year, data.month, 'monthly-saved'); }
      catch (error) { console.error('❌ [실시간] 근태 데이터 갱신 실패:', error); }
    });

    socket.on('attendance-checked-in', (data) => {
      devLog(`✨ [실시간] 출근 등록됨: ${data.employeeId}${data.isLate ? ' (지각)' : ''}`);
    });

    socket.on('attendance-checked-out', (data) => {
      devLog(`✨ [실시간] 퇴근 등록됨: ${data.employeeId} (근무시간: ${data.workMinutes}분)`);
    });

    socket.on('attendance-updated', (data) => {
      devLog(`✏️ [실시간] 근태 수정됨: ${data.employeeId}`);
    });

    socket.on('attendance-deleted', (data) => {
      devLog(`🗑️ [실시간] 근태 삭제됨: ${data.employeeId}`);
    });

    // 급여 실시간 업데이트
    const refreshPayroll = async (year, month, label) => {
      const response = await PayrollAPI.getMonthlyData(year, month);
      if (response && response.data) {
        const yearMonth = `${year}-${String(month).padStart(2, '0')}`;
        setPayrollByMonth((prev) => ({ ...prev, [yearMonth]: response.data }));
        devLog(`✅ [실시간] 급여 데이터 갱신 완료: ${year}년 ${month}월`);
      }
    };

    socket.on('payroll-bulk-uploaded', async (data) => {
      devLog(
        `✨ [실시간] 급여 대량 업로드됨: ${data.year}년 ${data.month}월 (추가: ${data.inserted}건, 수정: ${data.updated}건)`
      );
      try { await refreshPayroll(data.year, data.month, 'bulk-uploaded'); }
      catch (error) { console.error('❌ [실시간] 급여 데이터 갱신 실패:', error); }
    });

    socket.on('payroll-created', async (data) => {
      devLog(`✨ [실시간] 급여 생성됨: ${data.employeeId} (${data.year}년 ${data.month}월)`);
      try { await refreshPayroll(data.year, data.month, 'created'); }
      catch (error) { console.error('❌ [실시간] 급여 데이터 갱신 실패:', error); }
    });

    socket.on('payroll-updated', async (data) => {
      devLog(`✏️ [실시간] 급여 수정됨: ${data.employeeId} (${data.year}년 ${data.month}월)`);
      try { await refreshPayroll(data.year, data.month, 'updated'); }
      catch (error) { console.error('❌ [실시간] 급여 데이터 갱신 실패:', error); }
    });

    socket.on('payroll-deleted', async (data) => {
      devLog(`🗑️ [실시간] 급여 삭제됨: ${data.employeeId} (${data.year}년 ${data.month}월)`);
      try { await refreshPayroll(data.year, data.month, 'deleted'); }
      catch (error) { console.error('❌ [실시간] 급여 데이터 갱신 실패:', error); }
    });

    // 평가 실시간 업데이트
    const refreshEvaluations = async (label) => {
      const evaluations = await EvaluationAPI.list();
      if (evaluations && Array.isArray(evaluations)) {
        setEvaluationData(evaluations);
      }
    };

    socket.on('evaluation-created', async (data) => {
      devLog(`✨ [실시간] 평가 생성됨: ${data.name} (${data.year}년 - ${data.grade}등급)`);
      try { await refreshEvaluations('created'); }
      catch (error) { console.error('❌ [실시간] 평가 데이터 갱신 실패:', error); }
    });

    socket.on('evaluation-updated', async (data) => {
      devLog(`✏️ [실시간] 평가 수정됨: ${data.name} (${data.year}년 - ${data.grade}등급)`);
      try { await refreshEvaluations('updated'); }
      catch (error) { console.error('❌ [실시간] 평가 데이터 갱신 실패:', error); }
    });

    socket.on('evaluation-deleted', async (data) => {
      devLog(`🗑️ [실시간] 평가 삭제됨: ${data.name} (${data.year}년)`);
      try { await refreshEvaluations('deleted'); }
      catch (error) { console.error('❌ [실시간] 평가 데이터 갱신 실패:', error); }
    });

    // 안전사고 실시간 업데이트
    const refreshSafetyAccidents = async (label, allowEmpty = false) => {
      const accidents = await SafetyAccidentAPI.list();
      if (accidents && Array.isArray(accidents)) {
        setSafetyAccidents(accidents.map((a) => ({ ...a, id: a._id || a.id })));
      } else if (allowEmpty) {
        setSafetyAccidents([]);
      }
    };

    socket.on('safety-accident-created', async (data) => {
      devLog(`✨ [실시간] 안전사고 등록됨: ${data.date} (${data.severity})`);
      try { await refreshSafetyAccidents('created'); }
      catch (error) { console.error('❌ [실시간] 안전사고 데이터 갱신 실패:', error); }
    });

    socket.on('safety-accident-updated', async (data) => {
      devLog(`✏️ [실시간] 안전사고 수정됨: ${data.date} (${data.severity})`);
      try { await refreshSafetyAccidents('updated'); }
      catch (error) { console.error('❌ [실시간] 안전사고 데이터 갱신 실패:', error); }
    });

    socket.on('safety-accident-deleted', async (data) => {
      devLog(`🗑️ [실시간] 안전사고 삭제됨: ${data.date}`);
      try { await refreshSafetyAccidents('deleted', true); }
      catch (error) { console.error('❌ [실시간] 안전사고 데이터 갱신 실패:', error); }
    });

    // 일정 실시간 업데이트
    const refreshSchedules = async (label, allowEmpty = false) => {
      const response = await ScheduleAPI.list();
      const schedules = response?.data || response || [];
      if (Array.isArray(schedules) && schedules.length > 0) {
        setScheduleEvents(schedules.map((schedule) => ({
          id: schedule._id || schedule.id,
          title: schedule.title,
          date: schedule.date?.split('T')[0] || schedule.date,
          startDate: schedule.startDate?.split('T')[0],
          endDate: schedule.endDate?.split('T')[0],
          type: schedule.type,
          category: schedule.category,
          isCustom: schedule.isCustom || false,
          description: schedule.description,
          color: schedule.color,
          createdBy: schedule.createdBy,
          participants: schedule.participants || [],
        })));
      } else if (allowEmpty) {
        setScheduleEvents([]);
      }
    };

    socket.on('schedule-created', async (data) => {
      devLog(`✨ [실시간] 일정 생성됨: ${data.title} (${data.date})`);
      try { await refreshSchedules('created'); }
      catch (error) { console.error('❌ [실시간] 일정 데이터 갱신 실패:', error); }
    });

    socket.on('schedule-updated', async (data) => {
      devLog(`✏️ [실시간] 일정 수정됨: ${data.title} (${data.date})`);
      try { await refreshSchedules('updated'); }
      catch (error) { console.error('❌ [실시간] 일정 데이터 갱신 실패:', error); }
    });

    socket.on('schedule-deleted', async (data) => {
      devLog(`🗑️ [실시간] 일정 삭제됨: ${data.title}`);
      try { await refreshSchedules('deleted', true); }
      catch (error) { console.error('❌ [실시간] 일정 데이터 갱신 실패:', error); }
    });

    // ✅ 휴일 실시간 업데이트 리스너
    const refreshHolidays = async (label) => {
      const currentYear = currentYearRef.current;
      const startYear = currentYear - 1;
      const endYear = currentYear + 1;
      const response = await HolidayAPI.getYearsHolidays(startYear, endYear);
      if (response.success && response.data) {
        const allCustomHolidays = {};
        Object.values(response.data).forEach((yearHolidays) => {
          Object.entries(yearHolidays).forEach(([date, name]) => {
            if (date.includes('-') && date.split('-').length === 3) {
              allCustomHolidays[date] = name;
            }
          });
        });
        setCustomHolidays(allCustomHolidays);
        devLog(`✅ [실시간] 휴일 데이터 갱신 완료`);
      }
    };

    socket.on('holiday-created', async (data) => {
      devLog(`✨ [실시간] 휴일 생성됨: ${data.title} (${data.date})`);
      try { await refreshHolidays('created'); }
      catch (error) { console.error('❌ [실시간] 휴일 데이터 갱신 실패:', error); }
    });

    socket.on('holiday-updated', async (data) => {
      devLog(`✏️ [실시간] 휴일 수정됨: ${data.title} (${data.date})`);
      try { await refreshHolidays('updated'); }
      catch (error) { console.error('❌ [실시간] 휴일 데이터 갱신 실패:', error); }
    });

    socket.on('holiday-deleted', async (data) => {
      devLog(`🗑️ [실시간] 휴일 삭제됨: ${data.title}`);
      try { await refreshHolidays('deleted'); }
      catch (error) { console.error('❌ [실시간] 휴일 데이터 갱신 실패:', error); }
    });

    socket.on('disconnect', () => {
      devLog('🔌 [전역 Socket] 연결 해제됨');
    });

    return () => {
      socket.removeAllListeners();
      if (socket.connected) {
        socket.disconnect();
      }
    };
  }, [currentUser?.id]); // [4차 패치] [currentUser] → [currentUser?.id]: employee sync 시 소켓 재생성 방지
};

export default useSocketSync;
